const fs   = require("fs");
const path = require("path");

function copyDirRecursive(srcDir, destDir) {
  if (!fs.existsSync(srcDir)) return;
  if (!fs.existsSync(destDir)) fs.mkdirSync(destDir, { recursive: true });
  fs.readdirSync(srcDir, { withFileTypes: true }).forEach((entry) => {
    const srcPath  = path.join(srcDir, entry.name);
    const destPath = path.join(destDir, entry.name);
    if (entry.isDirectory()) copyDirRecursive(srcPath, destPath);
    else fs.copyFileSync(srcPath, destPath);
  });
}

// ── Create dist ──────────────────────────────────────────────────
if (!fs.existsSync("dist")) fs.mkdirSync("dist");

// ── Generate firebase-config.js from Vercel env vars ────────────
const cfg = {
  FIREBASE_API_KEY:            process.env.FIREBASE_API_KEY            || "",
  FIREBASE_AUTH_DOMAIN:        process.env.FIREBASE_AUTH_DOMAIN        || "",
  FIREBASE_PROJECT_ID:         process.env.FIREBASE_PROJECT_ID         || "",
  FIREBASE_STORAGE_BUCKET:     process.env.FIREBASE_STORAGE_BUCKET     || "",
  FIREBASE_MESSAGING_SENDER_ID:process.env.FIREBASE_MESSAGING_SENDER_ID|| "",
  FIREBASE_APP_ID:             process.env.FIREBASE_APP_ID             || "",
};

const firebaseConfigContent = `// Auto-generated by build.js — do not edit
window.ENV = {
  FIREBASE_API_KEY:            "${cfg.FIREBASE_API_KEY}",
  FIREBASE_AUTH_DOMAIN:        "${cfg.FIREBASE_AUTH_DOMAIN}",
  FIREBASE_PROJECT_ID:         "${cfg.FIREBASE_PROJECT_ID}",
  FIREBASE_STORAGE_BUCKET:     "${cfg.FIREBASE_STORAGE_BUCKET}",
  FIREBASE_MESSAGING_SENDER_ID:"${cfg.FIREBASE_MESSAGING_SENDER_ID}",
  FIREBASE_APP_ID:             "${cfg.FIREBASE_APP_ID}",
};
`;

fs.writeFileSync(path.join("dist", "firebase-config.js"), firebaseConfigContent);
console.log("Generated: dist/firebase-config.js");

// ── Copy HTML files ──────────────────────────────────────────────
const htmlFiles = [
  "index.html",
  "announcements.html",
  "messageboard.html",
  "schools.html",
  "staff.html",
  "documents.html",
  "login.html",
];

htmlFiles.forEach((file) => {
  if (!fs.existsSync(file)) return;
  fs.copyFileSync(file, path.join("dist", file));
  console.log(`Copied: ${file}`);
});

// ── Copy auth-guard.js ───────────────────────────────────────────
if (fs.existsSync("auth-guard.js")) {
  fs.copyFileSync("auth-guard.js", path.join("dist", "auth-guard.js"));
  console.log("Copied: auth-guard.js");
}

// ── Copy static assets ───────────────────────────────────────────
if (fs.existsSync("resources")) {
  copyDirRecursive("resources", "dist/resources");
  console.log("Copied: resources/");
}

// ── Summary ──────────────────────────────────────────────────────
console.log("\nBuild completed successfully!");
console.log("Environment variables:");
Object.keys(cfg).forEach((key) => {
  console.log(`  ${key}: ${cfg[key] ? "[SET]" : "[NOT SET - login will fail]"}`);
});
